# Python CircleCI 2.1 configuration file.
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.13
    working_directory: ~/repo
    steps:
      # Step 1: obtenemos codigo fuente
      - checkout
      # Step 2: creamos venv e instalamos dependencias
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      # Step 3: ejecutamos linters y flake8 y lanzamos casos de prueba
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v
      - setup_remote_docker:
          docker_layer_caching: true
  deploy:
    docker:
      - image: cimg/python3.13
    working_directory: ~/repo
    steps:
      # Step 1: Docker build and push
      - run:
          name: Build and Push Docker
          command: |
            source venv/bin/activate
            #docker build -t poc/$IMAGE_NAME:$TAG .
            #echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            #docker push ideaslocas/$IMAGE_NAME:$TAG
workflows:
  build-workflow:
      jobs:
        - build
        - deploy:
            requires: build